### This workflow can be used to manually create new release versions from a tag push using e.g. VSCODE ###
on:
  push:
    tags:
      - 'v*'

name: Release to terraform public registry
jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4
      - 
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          name: '${{ github.ref_name }}'
          token: ${{ secrets.GITHUB_TOKEN }}