name: Version Bumpr

on:
  pull_request:
    types:
      - labeled
      - closed

jobs:
  version-check:
    runs-on: ubuntu-latest
    if: github.event.action == 'labeled'
    steps:
      - 
        uses: actions/checkout@v3
      - 
        uses: haya14busa/action-bumpr@v1

  version:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' && github.event.pull_request.merged
    steps:
      - 
        uses: actions/checkout@v3
      - 
        id: bumpr
        uses: haya14busa/action-bumpr@v1
        with: 
          default_bump_level: patch
      - 
        uses: haya14busa/action-update-semver@v1
        if: "!steps.bumpr.outputs.skip"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.bumpr.outputs.next_version }}